### ISSUE TITLE
General tidy up

### ISSUE THREAD

**Issue by cej25** [cej25/c4Root#134]
A list of tasks to cleanup the output and general code-cleanliness prior to s100

- [x] Fully optional to print detector mappings, everywhere
- [x] Remove extraneous debugging comments
- [x] Change FineTime warnings to be more helpful and less messy
- [ ] Disable irrelevant (for now) errors (FairBasePar and FairGeo) [I HAVE NO IDEA HOW TO DO THIS]
- [x] Re-generate AIDA and FATIMA VME structure headers to remove errors from startup
- [ ] Figure out multi-line flush to print helpful information on bad events (whiterabbit bad00bad, events lacking epoch etc) (ncurses?)

**Comment by Rooitier** [comment]
Just regarding the FairBasePar and FairGeo it seems in the Cmakelists it is being included. https://github.com/cej25/c4Root/blob/main/c4source%2FCMakeLists.txt

Maybe remove? It didn't panic when removed fortran dependency.

**Comment by cej25** [comment]
Backburner.
