### ISSUE TITLE
Whiterabbit correction on TAMEX events

### ISSUE THREAD

**Issue by jelarsso** [cej25/c4Root#137]
Since the tamex collection window is quite long it is nice to add the difference between the trigger and the event time to the WR timestamp. I tried this roughly but it was seemingly successful. This is nice to have when searching for longer isomers.
Currently it is not in the code, but commented out I believe.

**Comment by cej25** [comment]
i think we need to make sure we can easily distinguish the unaltered WR of the trigger at least if we do this

**Comment by cej25** [comment]
I believe this was completed.
