### ISSUE TITLE
AIDA Snapshot Histo broken

### ISSUE THREAD

**Issue by nichubbard** [cej25/c4Root#140]
In AidaOnlineSpectra.cxx AidaOnlineSpectra::Snapshot_Histo() the code loops through the per-DSSD histograms but saves them with the same name, this will mean only the last DSSD picture will actually be written, I think?

**Comment by Rooitier** [comment]
What data was this tested on?

**Comment by Rooitier** [comment]
See here :)

Please test the implementation. It compiles, but I don't have something where I run it with 2 DSSSDs

https://github.com/cej25/c4Root/pull/145

**Comment by nichubbard** [comment]
I will test in a bit
Yesterday I took a very brief test with the 2 DSSDs: /lustre/gamma/nhubbard/aida_2dssd_test_ucesb.lmd

Obviously only decay (noise) is present

**Comment by nichubbard** [comment]
Farewell, Snapshots o7
