### ISSUE TITLE
Randomly slowing down to 10 ev/s after around 10M events.

### ISSUE THREAD

**Issue by jelarsso** [cej25/c4Root#43]
Not sure of the reason.

**Comment by nichubbard** [comment]
Seemed to go away on lxg1330 by removing AIDA 

Trying on my laptop with bPlas+FATIMA+AIDA it made it to 30M with no slowdown, annoyingly

RAM usage was pretty normal, so it is not a memory leak probably

**Comment by nichubbard** [comment]
Now seems to happen instantly iwth AIDA sending data
Cause unknown but definitely AIDA related

if can repro on my laptop will debug, otherwise will try narrowing it down on lxg1330

**Comment by nichubbard** [comment]
Follow-up thought: Maybe it happens with an LMD file too? That'd make things a lot easier to test... will investigate

**Comment by Rooitier** [comment]
I will try nearline on .lmd files tomorrow. bplast and AIDA.

**Comment by nichubbard** [comment]
seems to be fixed with commit 1ecf51f, ran to 100M events on lxg1330 with no issues at all
