### ISSUE TITLE
ToT spectra show differences between Go4 and c4

### ISSUE THREAD

**Issue by cej25** [cej25/c4Root#44]
In looking at FATIMA Time Machine signals, we notice that the structure of the signals shown in Slow ToT spectra are slightly different comparing Go4's output with our own. We do not think there is simply an issue of binning; our only current idea is perhaps it is related to the epoch correction. This was not implemented correctly (or at all) in Go4 for FATIMA, and there may also be issues on our end.

**Comment by Rooitier** [comment]
This can likely be purely epochs as I changed PLASTIC_TWINPEAKS_Detector_System.cxx for bPlast and didn't do it for FATIMA as well. Will patch it soon.
