### ISSUE TITLE
Folders for Histograms

### ISSUE THREAD

**Issue by cej25** [cej25/c4Root#50]
For ROOT files generated NEARLINE/OFFLINE (not the Online server, which is already implemented)

This should absolutely be possible, and as we've seen quite useful.

**Comment by Rooitier** [comment]
- this is coming from using ->Draw() anywhere in the Analysis. Looking into Nic's implementation of files in AIDA and going to caste something similar to the rest of subsystem. Might need to redo the Snapshot histo method with individual canvases.

**Comment by Rooitier** [comment]
Okay, this is partially implemented for now. I will do the remaining subsystems later. The only problem is suppressing the already drawn histograms in the home directory of the online viewer.

I think it has to do with the the fact that at some level batch mode still has to be flagged as true (at least gpt seems to think so). I tried doing it on the analysis level (didnt wory), and on the macro (but this crashed instantly).

**Comment by cej25** [comment]
How do you mean partially implemented?

I should have been more specific in the OP (and I will edit to reflect) - Folders for Histograms in Nearline/Offline root files.

**Comment by Rooitier** [comment]
Partially, as in, I only did it for bplast for now. I will do it for the remaining subsystems tomorrow or over the weekend.

**Comment by Rooitier** [comment]
This is now essentially complete, excluding FRS and beam monitor which I will nip in the bud once the histograms for online are defined. 

Similar method can be carried over for Near/offline.
