### ISSUE TITLE
White Rabbit Analysis

### ISSUE THREAD

**Issue by nichubbard** [cej25/c4Root#51]
It would be nice to make some WR analysis plots in c4root
Some that never were in GO4 that is useful is a WR (trigger 3) vs WR (trigger 3) of different subsystems - this should be a very sharp narrow peak confirming the WR is stabe on both systems (like the 'GOOD' correlation on ucesb)

Also WR (trigger 1) vs WR (trigger 1) to best set tight gates for prompt/non-prompt things

AIDA is more complex because it has no trigger, but we should eventually do e.g. AIDA Implant Time - bPlast WR trigger 1
These are in Go4

**Comment by Rooitier** [comment]
I have implemented something basic, but I haven't tested it. It compiles and I will take a look soon. I didn't do WR (sys 1) vs WR (Sys2) but WR(1-2) and expect a peak in the histogram as well as pulser peak.

It probably runs like ass.

**Comment by Rooitier** [comment]
I added something to check the subsystem inclusion like what was done with the time machine in the steering macro.

**Comment by cej25** [comment]
This is done.
