### ISSUE TITLE
Save Snapshot Online

### ISSUE THREAD

**Issue by cej25** [cej25/c4Root#52]
We need a method to effectively save a snapshot of the online histograms in their current state, without terminating the macro.

**Comment by Rooitier** [comment]
ඞ I saw him faking FairTasks in storage!!!

Reopened to resnap and save to sensible directory or storage spot for future experiments.

**Comment by Rooitier** [comment]
Snapshot working:
- [ ] FATIMA
- [ ] bPlast
- [ ] FATIMA VME
- [ ] AIDA
- [ ] DEGAS
- [ ] TM
- [ ] WR
- [ ] FRS ?
- [ ] Meme monitor

Reset:

- [ ] FATIMA
- [ ] bPlast
- [ ] FATIMA VME
- [ ] AIDA
- [ ] DEGAS
- [ ] TM
- [ ] WR
- [ ] FRS ?
- [ ] Meme monitor
