### ISSUE TITLE
FRS src accessing config

### ISSUE THREAD

**Issue by cej25** [cej25/c4Root#57]
FRS Source Code (and probably other areas) will need to access some shared config files on a by-experiment basis, so we need a way to do this without anyone having to change the source code... (for casual users).

For now, in /config I have set up a file `"frs_config.h"` - this will be included in src code files.
This file has an `#include` statement for the experiment-specific config file `"NovTest/frs_config_NovTest.h"`. Only this line in "frs_config.h" needs changing by a user.

Does anyone have any idea/suggestions/improvements for this?

**Comment by jelarsso** [comment]
I suggest we rather make a class that contains the parameters in c4Root, using maybe the already implemented FairRoot functions. And then make a function in the module that converts the raw data file from the FRS group into the format we implement in the code. This way the user need not to recompile the code but can rather change the steering macro.

**Comment by cej25** [comment]
This can be closed I believe.
tha
Our current structure is that we have a file "setup.h" in /config/. This includes the particular experiment setup-files that the code is compiled for, and source code simply does #include "setup.h".

So one has to change "setup.h" to include _their_ experiment when compiling, but then everything works smoothly. I think this is nicest? 

We can look at a solution where the code never needs to be compiled later, I think (post this coming beamtime).
