### ISSUE TITLE
detector mapping for bplast that is more comprehensive

### ISSUE THREAD

**Issue by Rooitier** [cej25/c4Root#60]
make a detector mapping that is ready that more clearly describes the position of channels of the detector.

"it is A LOT. nobody has more channels than me. some might even say i have the most."

**Comment by cej25** [comment]
Can this be closed?

**Comment by Rooitier** [comment]
Not yet, I need to add it to bPlast histograms and then organise them by up and down stream -- this is a trivial step. Will try to finish this week.
