### ISSUE TITLE
Options to turn off debugging statistics

### ISSUE THREAD

**Issue by nichubbard** [cej25/c4Root#61]
the bPlas prints a lot of statistics when it's destructed which is useful especially for developers but also spams the console a lot for people who aren't really interested, might be good to have an option to turn it off (I might add some for AIDA with an option too :) )

Pedantic: Also on virgo etc you shouldn't put the terminal colours in log files really [isatty(3)](https://man7.org/linux/man-pages/man3/isatty.3.html)

**Comment by Rooitier** [comment]
Currently I had implemented a fix in (Pull request #80 ) that always has printing statistics turned off. If one wants to view the statistics you can add a Boolean fPrintStatistics = true; in the steering macro to print statistics.

**Comment by cej25** [comment]
This request was resolved?

**Comment by Rooitier** [comment]
It will be once you complete the pull request ;)
