### ISSUE TITLE
FRS Correlations

### ISSUE THREAD

**Issue by cej25** [cej25/c4Root#69]
There are many bits and pieces to tidy and fix, but the next big step is looking at correlations, particularly with the FRS of course.

Should we have a separate class for correlations between FRS-{each subsystem}?  This would allow us to keep our strong modularity. 

The histograms and such that are produced should be done with a separate class compared with the raw FRS detector-check histograms, and even the analysed FRS hit histograms (Z, A/Q etc).

**Comment by nichubbard** [comment]
Splitting it up makes sense as each subsystem will have slightly different goals from correlations
e.g. AIDA+FRS is interested in AIDA implants and their PID whereas HPGe+FRS would be looking at isomers some ns after the flash

There should be some common routines for e.g. making/checking PID gates and conditions though

**Comment by cej25** [comment]
Unpolished but procedures now in place and FRS-AIDA (appear to be?) working. I will open separate issues for specific correlations.
