### ISSUE TITLE
FRS gates

### ISSUE THREAD

**Issue by cej25** [cej25/c4Root#81]
My feeling is that the best way to handle this means the following:

- Adding / Removing / Changing gates should not require changing source code and/or recompilation.
- Users can have as many gates and "points" on their polygon as they like without breaking something (although there will be a strong recommendation. For example current Go4 hardcodes a limit of 8 x 8-sided polygons).

Multiple tasks will need access to these gate objects (TCutGs seems best, FairRoot does not have the equivalent of a TGo4PolyCond that I have seen?).

In the steering macro, users can define (or rather alter a default) vector of FRS Gate-filenames. This vector will attempt to read such files and create an array of TCutG objects, which are passed along to the necessary tasks. 

This, I believe, would not require recompiling (?) - a user would simply need to create a TCUTG in a ROOT browser, and paste the x / y points in a text file. Defaults for examples (and backup) would be provided. 

Does this seem sensible?

**Comment by nichubbard** [comment]
Could we read TCutGs directly from e.g. a C macro? I think it's quite easy to make a TCutG and save it, then no dealing with pasting the x /  y points faff. 

Otherwise it should avoid compiling, only steering macro is changed. 

Can yuo draw the TCutG in the online spectra? or would you have to make a snapshot and work on there

**Comment by cej25** [comment]
> Could we read TCutGs directly from e.g. a C macro? I think it's quite easy to make a TCutG and save it, then no dealing with pasting the x / y points faff.

Yeah, actually we can just read the TCutG directly from the macro. 

> Otherwise it should avoid compiling, only steering macro is changed.
> Can yuo draw the TCutG in the online spectra? or would you have to make a snapshot and work on there

Ok great, thought so.

My understanding is that the THttpServer does not support this, so you would need to take a snapshot and work on there. It's not immediately clear to me what our way around this is without simply building some GUI.

**Comment by Rooitier** [comment]
R3BRoot has an implementation of this: https://github.com/R3BRootGroup/R3BRoot/blob/dev/r3bbase/R3BTcutPar.cxx

**Comment by cej25** [comment]
I think I can close this. It is possible to read in N gates of M types and pass these along to Analysis/Correlation procedures.
