### ISSUE TITLE
Add AIDA "scaler" histograms for implants and decays

### ISSUE THREAD

**Issue by nichubbard** [cej25/c4Root#82]
Can see how the rate in AIDA varies with time, should be simple

**Comment by nichubbard** [comment]
Should this be per DSSD or global? What do people think?

**Comment by cej25** [comment]
A "per DSSD" is probably quite useful, particularly as we test the new BB7 layer. We can also see how "stopping" changes in layers over time?

**Comment by nichubbard** [comment]
Implant per DSSD
*Stopped* Implant per DSSD
Decay per DSSD

Maybe?
