### ISSUE TITLE
FATIMA VME

### ISSUE THREAD

**Issue by cej25** [cej25/c4Root#89]
Obviously its still unclear on what decision (if any) will be made regarding using FATIMA VME in conjunction with TAMEX, but we need to set up an unpacker, reader and further tasks to handle this type of data.

s452 has FATIMA VME data, so I'll use this.

- [x] Unpacker (UCESB)
- [x] Reader
- [x] Raw2Cal
- [x] Online Spectra 
- [x] Correlations options (for Nearline)

**Comment by cej25** [comment]
s452 has FATIMA VME data, so I'll use this.

- [ ] Unpacker (UCESB)
- [ ] Reader
- [ ] Raw2Cal
- [ ] Correlations options (vs. TAMEX)

**Comment by nichubbard** [comment]
The most likely situation is it won't be FATIMA VME **and** TAMEX, but rather one or the other (hopefully TAMEX) 
just an FYI

**Comment by cej25** [comment]
Yep, I overheard some of this today. But means that both definitely need to be ready to use, right? If TAMEX craps out, we need to immediately be able to use VME.
