### ISSUE TITLE
Virtual Messhütte Integration

### ISSUE THREAD

**Issue by nichubbard** [cej25/c4Root#96]
Moving here to keep all things in one place

We should test c4root working with the Virtual Messhütte

In theory if it is running HTTP server on port 5000 on lxg1301 it should be accessible but we should check it works before the dry run

We should also prepare links to add to the home page linking to specific plots/layouts for each detector 
(These will also be automatically uploaded to ELOG regularly)

- [x] Check c4Root can be accessed from VM
- [x] Prepare links for AIDA
- [x] Prepare links for FRS
- [x] Prepare links for bPlast
- [x] Prepare links for FATIMA
- [x] Prepare links for DEGAS
- [x] Prepare links for Misc
- [ ] Think about nearline section

**Comment by Rooitier** [comment]
I made some links that I left on the Fairroot mattermost.

Some of the links are not working/broken.

AIDA needs inclusion of DSSSD2 if links from DSSSD1 can be faithfully copied and changed it should work.

Bplast TAMEX card hit patterns - I need to commit still.

Time machine needs folders... Qol improvement.

**Comment by nichubbard** [comment]
I think it was all done, except nearline which people didn't do correctly enough, or use?
